//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSSoft.Font.ApplicationHost.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JSSoft.Font.ApplicationHost.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   _Find과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Find {
            get {
                return ResourceManager.GetString("Button_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Search by Character과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CheckBox_SearchByCharacter {
            get {
                return ResourceManager.GetString("CheckBox_SearchByCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Navigate Backward과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Command_NavigateBackward {
            get {
                return ResourceManager.GetString("Command_NavigateBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Navigate Forward과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Command_NavigateForward {
            get {
                return ResourceManager.GetString("Command_NavigateForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font already open.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_FontAlreadyOpen {
            get {
                return ResourceManager.GetString("Exception_FontAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font does not open.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_FontDoesNotOpen {
            get {
                return ResourceManager.GetString("Exception_FontDoesNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid settings path과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_InvalidSettingsPath {
            get {
                return ResourceManager.GetString("Exception_InvalidSettingsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   length must be 1.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_LengthMustBeOne {
            get {
                return ResourceManager.GetString("Exception_LengthMustBeOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   min must be less than max과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_MinLessMax {
            get {
                return ResourceManager.GetString("Exception_MinLessMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   font files (*.otf;*.ttc;*.ttf)|*.otf;*.ttc;*.ttf|all files (*.*)|*.*과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FontFilter {
            get {
                return ResourceManager.GetString("FontFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Background Color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_BackgroundColor {
            get {
                return ResourceManager.GetString("Label_BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _DPI과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_DPI {
            get {
                return ResourceManager.GetString("Label_DPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Font과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Font {
            get {
                return ResourceManager.GetString("Label_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Font Color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_FontColor {
            get {
                return ResourceManager.GetString("Label_FontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Padding과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Padding {
            get {
                return ResourceManager.GetString("Label_Padding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   P_adding Color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_PaddingColor {
            get {
                return ResourceManager.GetString("Label_PaddingColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Size과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Size {
            get {
                return ResourceManager.GetString("Label_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Spacing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Spacing {
            get {
                return ResourceManager.GetString("Label_Spacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Texture _Height과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_TextureHeight {
            get {
                return ResourceManager.GetString("Label_TextureHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Texture _Width과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_TextureWidth {
            get {
                return ResourceManager.GetString("Label_TextureWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unicode _Value과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UnicodeValue {
            get {
                return ResourceManager.GetString("Label_UnicodeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _About...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_About {
            get {
                return ResourceManager.GetString("MenuItem_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _CheckCharacter과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_CheckCharacter {
            get {
                return ResourceManager.GetString("MenuItem_CheckCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Check Character Group과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_CheckCharacterGroup {
            get {
                return ResourceManager.GetString("MenuItem_CheckCharacterGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Check Character Row과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_CheckCharacterRow {
            get {
                return ResourceManager.GetString("MenuItem_CheckCharacterRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Close과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Close {
            get {
                return ResourceManager.GetString("MenuItem_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Edit Export Settings...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_EditExportSettings {
            get {
                return ResourceManager.GetString("MenuItem_EditExportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Export...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Export {
            get {
                return ResourceManager.GetString("MenuItem_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_File {
            get {
                return ResourceManager.GetString("MenuItem_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Fint Character...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_FindCharacter {
            get {
                return ResourceManager.GetString("MenuItem_FindCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Help과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Help {
            get {
                return ResourceManager.GetString("MenuItem_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide _Property Window과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_HidePropertyWindow {
            get {
                return ResourceManager.GetString("MenuItem_HidePropertyWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Load Export Settings...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_LoadSettings {
            get {
                return ResourceManager.GetString("MenuItem_LoadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Open Font...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_OpenFont {
            get {
                return ResourceManager.GetString("MenuItem_OpenFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pre_view...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Preview {
            get {
                return ResourceManager.GetString("MenuItem_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Preview Character과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_PreviewCharacter {
            get {
                return ResourceManager.GetString("MenuItem_PreviewCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Quit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Quit {
            get {
                return ResourceManager.GetString("MenuItem_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recent Fonts과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_RecentFonts {
            get {
                return ResourceManager.GetString("MenuItem_RecentFonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recent Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_RecentSettings {
            get {
                return ResourceManager.GetString("MenuItem_RecentSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Save Character...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_SaveCharacter {
            get {
                return ResourceManager.GetString("MenuItem_SaveCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _SaveSettings...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_SaveSettings {
            get {
                return ResourceManager.GetString("MenuItem_SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Settings _As...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_SaveSettingsAs {
            get {
                return ResourceManager.GetString("MenuItem_SaveSettingsAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Select Characters...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_SelectCharacters {
            get {
                return ResourceManager.GetString("MenuItem_SelectCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show _Property Window과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_ShowPropertyWindow {
            get {
                return ResourceManager.GetString("MenuItem_ShowPropertyWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Tool과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Tool {
            get {
                return ResourceManager.GetString("MenuItem_Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Uncheck Character과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_UncheckCharacter {
            get {
                return ResourceManager.GetString("MenuItem_UncheckCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Uncheck Character Group과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_UncheckCharacterGroup {
            get {
                return ResourceManager.GetString("MenuItem_UncheckCharacterGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Uncheck Character Row과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_UncheckCharacterRow {
            get {
                return ResourceManager.GetString("MenuItem_UncheckCharacterRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _View과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_View {
            get {
                return ResourceManager.GetString("MenuItem_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom _In과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_ZoomIn {
            get {
                return ResourceManager.GetString("MenuItem_ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zomm _Out과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_ZoomOut {
            get {
                return ResourceManager.GetString("MenuItem_ZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   png files (*.png)|*.png|all files (*.*)|*.*과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PNGFilter {
            get {
                return ResourceManager.GetString("PNGFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_About {
            get {
                return ResourceManager.GetString("Title_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Character Info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_CharacterInfo {
            get {
                return ResourceManager.GetString("Title_CharacterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Export Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_EditExportSettings {
            get {
                return ResourceManager.GetString("Title_EditExportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find Character과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_FindCharacter {
            get {
                return ResourceManager.GetString("Title_FindCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font Info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_FontInfo {
            get {
                return ResourceManager.GetString("Title_FontInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font Options과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_FontOptions {
            get {
                return ResourceManager.GetString("Title_FontOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Group Info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_GroupInfo {
            get {
                return ResourceManager.GetString("Title_GroupInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preview과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_Preview {
            get {
                return ResourceManager.GetString("Title_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preview Character과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_PreviewCharacter {
            get {
                return ResourceManager.GetString("Title_PreviewCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Characters과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_SelectCharacters {
            get {
                return ResourceManager.GetString("Title_SelectCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_SelectColor {
            get {
                return ResourceManager.GetString("Title_SelectColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Font과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToolBarItem_OpenFont {
            get {
                return ResourceManager.GetString("ToolBarItem_OpenFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom In과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToolBarItem_ZoomIn {
            get {
                return ResourceManager.GetString("ToolBarItem_ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom Out과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToolBarItem_ZoomOut {
            get {
                return ResourceManager.GetString("ToolBarItem_ZoomOut", resourceCulture);
            }
        }
    }
}
