//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSSoft.Fonts.ApplicationHost.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JSSoft.Fonts.ApplicationHost.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Find.
        /// </summary>
        public static string Button_Find {
            get {
                return ResourceManager.GetString("Button_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Search by Character.
        /// </summary>
        public static string CheckBox_SearchByCharacter {
            get {
                return ResourceManager.GetString("CheckBox_SearchByCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate Backward.
        /// </summary>
        public static string Command_NavigateBackward {
            get {
                return ResourceManager.GetString("Command_NavigateBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate Forward.
        /// </summary>
        public static string Command_NavigateForward {
            get {
                return ResourceManager.GetString("Command_NavigateForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate any instances..
        /// </summary>
        public static string Exception_CannotFoundInstances {
            get {
                return ResourceManager.GetString("Exception_CannotFoundInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font already open..
        /// </summary>
        public static string Exception_FontAlreadyOpen {
            get {
                return ResourceManager.GetString("Exception_FontAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font does not open..
        /// </summary>
        public static string Exception_FontDoesNotOpen {
            get {
                return ResourceManager.GetString("Exception_FontDoesNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid settings path..
        /// </summary>
        public static string Exception_InvalidSettingsPath {
            get {
                return ResourceManager.GetString("Exception_InvalidSettingsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to length must be 1..
        /// </summary>
        public static string Exception_LengthMustBeOne {
            get {
                return ResourceManager.GetString("Exception_LengthMustBeOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min must be less than max.
        /// </summary>
        public static string Exception_MinLessMax {
            get {
                return ResourceManager.GetString("Exception_MinLessMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to font files (*.otf;*.ttc;*.ttf)|*.otf;*.ttc;*.ttf|all files (*.*)|*.*.
        /// </summary>
        public static string FontFilter {
            get {
                return ResourceManager.GetString("FontFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Background Color.
        /// </summary>
        public static string Label_BackgroundColor {
            get {
                return ResourceManager.GetString("Label_BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Characters to Select.
        /// </summary>
        public static string Label_CharacterToSelect {
            get {
                return ResourceManager.GetString("Label_CharacterToSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _DPI.
        /// </summary>
        public static string Label_DPI {
            get {
                return ResourceManager.GetString("Label_DPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Font.
        /// </summary>
        public static string Label_Font {
            get {
                return ResourceManager.GetString("Label_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Font Color.
        /// </summary>
        public static string Label_FontColor {
            get {
                return ResourceManager.GetString("Label_FontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Padding.
        /// </summary>
        public static string Label_Padding {
            get {
                return ResourceManager.GetString("Label_Padding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P_adding Color.
        /// </summary>
        public static string Label_PaddingColor {
            get {
                return ResourceManager.GetString("Label_PaddingColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Size.
        /// </summary>
        public static string Label_Size {
            get {
                return ResourceManager.GetString("Label_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Spacing.
        /// </summary>
        public static string Label_Spacing {
            get {
                return ResourceManager.GetString("Label_Spacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture _Height.
        /// </summary>
        public static string Label_TextureHeight {
            get {
                return ResourceManager.GetString("Label_TextureHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture _Width.
        /// </summary>
        public static string Label_TextureWidth {
            get {
                return ResourceManager.GetString("Label_TextureWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode _Value.
        /// </summary>
        public static string Label_UnicodeValue {
            get {
                return ResourceManager.GetString("Label_UnicodeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About....
        /// </summary>
        public static string MenuItem_About {
            get {
                return ResourceManager.GetString("MenuItem_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _CheckCharacter.
        /// </summary>
        public static string MenuItem_CheckCharacter {
            get {
                return ResourceManager.GetString("MenuItem_CheckCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Check Character Group.
        /// </summary>
        public static string MenuItem_CheckCharacterGroup {
            get {
                return ResourceManager.GetString("MenuItem_CheckCharacterGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Check Character Row.
        /// </summary>
        public static string MenuItem_CheckCharacterRow {
            get {
                return ResourceManager.GetString("MenuItem_CheckCharacterRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string MenuItem_Close {
            get {
                return ResourceManager.GetString("MenuItem_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit Export Settings....
        /// </summary>
        public static string MenuItem_EditExportSettings {
            get {
                return ResourceManager.GetString("MenuItem_EditExportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Export....
        /// </summary>
        public static string MenuItem_Export {
            get {
                return ResourceManager.GetString("MenuItem_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MenuItem_File {
            get {
                return ResourceManager.GetString("MenuItem_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Fint Character....
        /// </summary>
        public static string MenuItem_FindCharacter {
            get {
                return ResourceManager.GetString("MenuItem_FindCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string MenuItem_Help {
            get {
                return ResourceManager.GetString("MenuItem_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide _Property Window.
        /// </summary>
        public static string MenuItem_HidePropertyWindow {
            get {
                return ResourceManager.GetString("MenuItem_HidePropertyWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Load Export Settings....
        /// </summary>
        public static string MenuItem_LoadSettings {
            get {
                return ResourceManager.GetString("MenuItem_LoadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open Font....
        /// </summary>
        public static string MenuItem_OpenFont {
            get {
                return ResourceManager.GetString("MenuItem_OpenFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre_view....
        /// </summary>
        public static string MenuItem_Preview {
            get {
                return ResourceManager.GetString("MenuItem_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Preview Character.
        /// </summary>
        public static string MenuItem_PreviewCharacter {
            get {
                return ResourceManager.GetString("MenuItem_PreviewCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Quit.
        /// </summary>
        public static string MenuItem_Quit {
            get {
                return ResourceManager.GetString("MenuItem_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Fonts.
        /// </summary>
        public static string MenuItem_RecentFonts {
            get {
                return ResourceManager.GetString("MenuItem_RecentFonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Settings.
        /// </summary>
        public static string MenuItem_RecentSettings {
            get {
                return ResourceManager.GetString("MenuItem_RecentSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save Character....
        /// </summary>
        public static string MenuItem_SaveCharacter {
            get {
                return ResourceManager.GetString("MenuItem_SaveCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _SaveSettings....
        /// </summary>
        public static string MenuItem_SaveSettings {
            get {
                return ResourceManager.GetString("MenuItem_SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Settings _As....
        /// </summary>
        public static string MenuItem_SaveSettingsAs {
            get {
                return ResourceManager.GetString("MenuItem_SaveSettingsAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Select Characters....
        /// </summary>
        public static string MenuItem_SelectCharacters {
            get {
                return ResourceManager.GetString("MenuItem_SelectCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show _Property Window.
        /// </summary>
        public static string MenuItem_ShowPropertyWindow {
            get {
                return ResourceManager.GetString("MenuItem_ShowPropertyWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tool.
        /// </summary>
        public static string MenuItem_Tool {
            get {
                return ResourceManager.GetString("MenuItem_Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Uncheck Character.
        /// </summary>
        public static string MenuItem_UncheckCharacter {
            get {
                return ResourceManager.GetString("MenuItem_UncheckCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Uncheck Character Group.
        /// </summary>
        public static string MenuItem_UncheckCharacterGroup {
            get {
                return ResourceManager.GetString("MenuItem_UncheckCharacterGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Uncheck Character Row.
        /// </summary>
        public static string MenuItem_UncheckCharacterRow {
            get {
                return ResourceManager.GetString("MenuItem_UncheckCharacterRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string MenuItem_View {
            get {
                return ResourceManager.GetString("MenuItem_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom _In.
        /// </summary>
        public static string MenuItem_ZoomIn {
            get {
                return ResourceManager.GetString("MenuItem_ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zomm _Out.
        /// </summary>
        public static string MenuItem_ZoomOut {
            get {
                return ResourceManager.GetString("MenuItem_ZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to png files (*.png)|*.png|all files (*.*)|*.*.
        /// </summary>
        public static string PNGFilter {
            get {
                return ResourceManager.GetString("PNGFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Title_About {
            get {
                return ResourceManager.GetString("Title_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Info.
        /// </summary>
        public static string Title_CharacterInfo {
            get {
                return ResourceManager.GetString("Title_CharacterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Export Settings.
        /// </summary>
        public static string Title_EditExportSettings {
            get {
                return ResourceManager.GetString("Title_EditExportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Character.
        /// </summary>
        public static string Title_FindCharacter {
            get {
                return ResourceManager.GetString("Title_FindCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Info.
        /// </summary>
        public static string Title_FontInfo {
            get {
                return ResourceManager.GetString("Title_FontInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Options.
        /// </summary>
        public static string Title_FontOptions {
            get {
                return ResourceManager.GetString("Title_FontOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Info.
        /// </summary>
        public static string Title_GroupInfo {
            get {
                return ResourceManager.GetString("Title_GroupInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Title_Preview {
            get {
                return ResourceManager.GetString("Title_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Character.
        /// </summary>
        public static string Title_PreviewCharacter {
            get {
                return ResourceManager.GetString("Title_PreviewCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Characters.
        /// </summary>
        public static string Title_SelectCharacters {
            get {
                return ResourceManager.GetString("Title_SelectCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Color.
        /// </summary>
        public static string Title_SelectColor {
            get {
                return ResourceManager.GetString("Title_SelectColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Font.
        /// </summary>
        public static string ToolBarItem_OpenFont {
            get {
                return ResourceManager.GetString("ToolBarItem_OpenFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        public static string ToolBarItem_ZoomIn {
            get {
                return ResourceManager.GetString("ToolBarItem_ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        public static string ToolBarItem_ZoomOut {
            get {
                return ResourceManager.GetString("ToolBarItem_ZoomOut", resourceCulture);
            }
        }
    }
}
